Test

diff --git a/.github/workflows/.deployer.yml b/.github/workflows/.deployer.yml
--- a/.github/workflows/.deployer.yml
+++ b/.github/workflows/.deployer.yml
@@ -177,9 +177,14 @@ jobs:
             # oc delete po --field-selector=status.phase==Succeeded || true
 
       - env:
-          results: ${{ toJSON(steps.deploy)}}
+          outputs: ${{ toJSON(steps.deploy.outputs) }}
         run: |
-          echo "results?: ${{ env.results }}"
+          # Verify outputs
+          echo "Outputs: ${{ env.outputs }}"
+          if [ "${{ steps.deploy.outputs.triggered }}" != "true" ]; then
+            echo "Error!  Verify outputs."
+            exit 1
+          fi
 
   check:
     name: Check
