Support init for db in _deploy

diff --git a/.github/workflows/_deploy.yml b/.github/workflows/_deploy.yml
--- a/.github/workflows/_deploy.yml
+++ b/.github/workflows/_deploy.yml
@@ -7,6 +7,10 @@ on:
         type: string
         required: true
         description: Component (e.g. backend, frontend), also used as path
+      overwrite:
+        type: string
+        required: true
+        description: Replace existing objects/artifacts?
       template_file:
         type: string
         required: true
@@ -49,8 +53,13 @@ jobs:
           # Clean previous images
           oc delete is/${IS} || true
 
-          # Apply processed template
-          oc apply -f - <<< "${TEMPLATE}"
+          # Apply (overwrites) or create (does not overwrite) using processed template
+          if [ "${{ inputs.overwrite }}" == "true" ]; then
+            oc apply -f - <<< "${TEMPLATE}"
+          else
+            # Suppress AlreadyExists errors and expected failure
+            oc create -f - 2>&1 <<< "${TEMPLATE}" | { grep -v "(AlreadyExists)" || true; }
+          fi
 
           # Follow any active rollouts (see deploymentconfigs)
           oc rollout status dc/${DC} -w
