Testing

diff --git a/.github/workflows/_deploy.yml b/.github/workflows/_deploy.yml
--- a/.github/workflows/_deploy.yml
+++ b/.github/workflows/_deploy.yml
@@ -59,6 +59,8 @@ jobs:
 
       - name: Deployment Verification
         run: |
+          set -eux
+
           # Pick out a url (host+path), if in template
           URL=$( \
             oc process -f ${{ inputs.template_file }} ${{ inputs.template_vars }} --local \
@@ -66,9 +68,10 @@ jobs:
           )
 
           # If URL exists and is usable (e.g. at least a hostname), then test it
+          echo -e "\nChecking ${URL}\n"
           if [ ! -z "${URL%/*}" ] && [ $(curl -Lso /dev/null -w "%{http_code}" "${URL}") -ne 200 ]
           then
-              echo "Status != 200 for ${{ inputs.url }}"
+              echo "Failure!  Status != 200"
               exit 1
           fi
           echo "Deployment successful"
