Simplify

diff --git a/.github/workflows/pr-open.yml b/.github/workflows/pr-open.yml
--- a/.github/workflows/pr-open.yml
+++ b/.github/workflows/pr-open.yml
@@ -53,16 +53,6 @@ jobs:
     if: always()
     runs-on: ubuntu-22.04
     steps:
-      - run: echo '${{ toJSON(needs) }} | jq .'
-      - run: echo '${{ toJSON(needs) }}' | jq -e 'to_entries | all(.value.result == "success")'
-      - run: |
-          # View results
-          echo "needs.*.result: ${{ toJson(needs.*.result) }}"
       - if: contains(needs.*.result, 'failure')
-        run: |
-          # Job failure found
-          echo "At least one job has failed"
-          exit 1
-      - run: |
-          echo "Purposeful fail!"
-          exit 1
+        run: echo "At least one job has failed." && exit 1
+      - run: echo "Success!"
