Roll more into action

diff --git a/.github/workflows/scheduled.yml b/.github/workflows/scheduled.yml
--- a/.github/workflows/scheduled.yml
+++ b/.github/workflows/scheduled.yml
@@ -18,42 +18,40 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 10
     steps:
-      - name: Install OpenShift CLI (oc) and Login
+      - name: Clean up Helm Releases
         uses: bcgov/action-oc-runner@main
         with:
           oc_namespace: ${{ secrets.oc_namespace }}
           oc_token: ${{ secrets.oc_token }}
           oc_server: ${{ vars.oc_server }}
+          commands: |
+            # Catch errors, unset variables, and pipe failures (e.g. grep || true )
+            set -euo pipefail
 
-      - name: Clean up Helm Releases
-        run: |
-          # Catch errors, unset variables, and pipe failures (e.g. grep || true )
-          set -euo pipefail
+            # Echos
+            echo "Delete stale Helm releases"
+            echo "Cutoff: ${{ env.CUTOFF }}"
 
-          # Echos
-          echo "Delete stale Helm releases"
-          echo "Cutoff: ${{ env.CUTOFF }}"
+            # Before date, list of releases
+            BEFORE=$(date +%s -d "${{ env.CUTOFF }}")
+            RELEASES=$(helm ls -aq | grep ${{ github.event.repository.name }} || :)
 
-          # Before date, list of releases
-          BEFORE=$(date +%s -d "${{ env.CUTOFF }}")
-          RELEASES=$(helm ls -aq | grep ${{ github.event.repository.name }} || :)
+            # If releases, then iterate
+            [ -z "${RELEASES}" ]|| for r in ${RELEASES[@]}; do
 
-          # If releases, then iterate
-          [ -z "${RELEASES}" ]|| for r in ${RELEASES[@]}; do
+              # Get last update and convert the date
+              UPDATED=$(date "+%s" -d <<< echo $(helm status $r -o json | jq -r .info.last_deployed))
 
-            # Get last update and convert the date
-            UPDATED=$(date "+%s" -d <<< echo $(helm status $r -o json | jq -r .info.last_deployed))
-
-            # Compare to cutoff and delete as necessary
-            if [[ ${UPDATED} < ${BEFORE} ]]; then
-              echo -e "\nOlder than cutoff: ${r}"
-              helm uninstall --no-hooks ${r}
-              oc delete pvc/${r}-bitnami-pg-0 || true
-            else
-              echo -e "\nNewer than cutoff: ${r}"
-              echo "No need to delete"
-            fi
-          done
+              # Compare to cutoff and delete as necessary
+              if [[ ${UPDATED} < ${BEFORE} ]]; then
+                echo -e "\nOlder than cutoff: ${r}"
+                helm uninstall --no-hooks ${r}
+                oc delete pvc/${r}-bitnami-pg-0 || true
+              else
+                echo -e "\nNewer than cutoff: ${r}"
+                echo "No need to delete"
+              fi
+            done
 
   # https://github.com/bcgov/quickstart-openshift-helpers
   schema-spy:
