Add .tests to .scheduled

diff --git a/.github/workflows/scheduled.yml b/.github/workflows/scheduled.yml
--- a/.github/workflows/scheduled.yml
+++ b/.github/workflows/scheduled.yml
@@ -9,28 +9,45 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
-  tests:
-    name: Tests
-    uses: ./.github/workflows/.tests.yml
-
-  zap_scan:
-    runs-on: ubuntu-latest
-    name: Penetration Tests
+  ageOutPRs:
+    name: PR Env Purge
     env:
-      DOMAIN: apps.silver.devops.gov.bc.ca
-      PREFIX: ${{ github.event.repository.name }}-test
-    strategy:
-      matrix:
-        name: [backend, frontend]
+      # https://tecadmin.net/getting-yesterdays-date-in-bash/
+      CUTOFF: "1 week ago"
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
     steps:
-      - name: ZAP Scan
-        uses: zaproxy/action-full-scan@v0.9.0
-        with:
-          allow_issue_writing: true
-          artifact_name: "zap_${{ matrix.name }}"
-          cmd_options: "-a"
-          issue_title: "ZAP: ${{ matrix.name }}"
-          target: https://${{ env.PREFIX }}-${{ matrix.name }}.${{ env.DOMAIN }}
+      - name: Clean up Helm Releases
+        run: |
+          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
+          oc project ${{ vars.OC_NAMESPACE }} # Safeguard!
+
+          # Catch errors, unset variables, and pipe failures (e.g. grep || true )
+          set -euo pipefail
+
+          # Echos
+          echo "Delete stale Helm releases"
+          echo "Cutoff: ${{ env.CUTOFF }}"
+
+          # Before date, list of releases
+          BEFORE=$(date +%s -d "${{ env.CUTOFF }}")
+          RELEASES=$(helm ls -aq | grep ${{ github.event.repository.name }} || :)
+
+          # If releases, then iterate
+          [ -z "${RELEASES}" ]|| for r in ${RELEASES[@]}; do
+
+            # Get last update and convert the date
+            UPDATED=$(date "+%s" -d <<< echo $(helm status $r -o json | jq -r .info.last_deployed))
+
+            # Compare to cutoff and delete as necessary
+            if [[ ${UPDATED} < ${BEFORE} ]]; then
+              echo -e "\nOlder than cutoff: ${r}"
+              helm uninstall --no-hooks ${r}
+            else
+              echo -e "\nNewer than cutoff: ${r}"
+              echo "No need to delete"
+            fi
+          done
 
   generate-schema-spy:
     name: Generate SchemaSpy Documentation
@@ -75,42 +92,25 @@ jobs:
           folder: output
           target-folder: schemaspy
 
-  ageOutPRs:
-    name: PR Env Purge
-    env:
-      # https://tecadmin.net/getting-yesterdays-date-in-bash/
-      CUTOFF: "1 week ago"
+  tests:
+    name: Tests
+    uses: ./.github/workflows/.tests.yml
+
+  zap_scan:
     runs-on: ubuntu-latest
-    timeout-minutes: 10
+    name: Penetration Tests
+    env:
+      DOMAIN: apps.silver.devops.gov.bc.ca
+      PREFIX: ${{ github.event.repository.name }}-test
+    strategy:
+      matrix:
+        name: [backend, frontend]
     steps:
-      - name: Clean up Helm Releases
-        run: |
-          oc login --token=${{ secrets.OC_TOKEN }} --server=${{ vars.OC_SERVER }}
-          oc project ${{ vars.OC_NAMESPACE }} # Safeguard!
-
-          # Catch errors, unset variables, and pipe failures (e.g. grep || true )
-          set -euo pipefail
-
-          # Echos
-          echo "Delete stale Helm releases"
-          echo "Cutoff: ${{ env.CUTOFF }}"
-
-          # Before date, list of releases
-          BEFORE=$(date +%s -d "${{ env.CUTOFF }}")
-          RELEASES=$(helm ls -aq | grep ${{ github.event.repository.name }} || :)
-
-          # If releases, then iterate
-          [ -z "${RELEASES}" ]|| for r in ${RELEASES[@]}; do
-
-            # Get last update and convert the date
-            UPDATED=$(date "+%s" -d <<< echo $(helm status $r -o json | jq -r .info.last_deployed))
-
-            # Compare to cutoff and delete as necessary
-            if [[ ${UPDATED} < ${BEFORE} ]]; then
-              echo -e "\nOlder than cutoff: ${r}"
-              helm uninstall --no-hooks ${r}
-            else
-              echo -e "\nNewer than cutoff: ${r}"
-              echo "No need to delete"
-            fi
-          done
+      - name: ZAP Scan
+        uses: zaproxy/action-full-scan@v0.9.0
+        with:
+          allow_issue_writing: true
+          artifact_name: "zap_${{ matrix.name }}"
+          cmd_options: "-a"
+          issue_title: "ZAP: ${{ matrix.name }}"
+          target: https://${{ env.PREFIX }}-${{ matrix.name }}.${{ env.DOMAIN }}
